# Generated by Django 2.2.10 on 2020-03-07 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sportsnews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsnews',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
