# Generated by Django 2.0 on 2020-01-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('video_url', models.URLField()),
                ('inframe_url', models.URLField()),
                ('img_url', models.URLField()),
            ],
        ),
    ]
