# Generated by Django 2.2 on 2019-04-29 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190428_1047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
