# Generated by Django 2.0 on 2019-05-14 12:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190502_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='style',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
    ]
