# Generated by Django 2.0 on 2019-05-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blog_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='style',
            field=models.TextField(default=0),
        ),
    ]
