# Generated by Django 2.0 on 2019-05-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190516_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='canread',
            field=models.IntegerField(default=1),
        ),
    ]
