# Generated by Django 2.0 on 2019-05-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blog_canread'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='script',
            field=models.TextField(default=''),
        ),
    ]
