# Generated by Django 2.0 on 2020-02-12 02:08

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blog_script'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='canread',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='script',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='style',
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
