# Generated by Django 2.0 on 2020-02-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200212_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='canread',
            field=models.IntegerField(default=1),
        ),
    ]
