# Generated by Django 2.0 on 2020-02-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_blog_canread'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='script',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='style',
            field=models.TextField(default=0),
        ),
    ]
